title: Cutter Dawes
email: cutter@dawes.org
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://cutterdawes.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts: {}

permalink: /blog/:year-:month-:day-:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from