title: Cutter Dawes
email: cutter@dawes.org
description: ""
url: "https://cutterdawes.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts: {}

permalink: /blog/:year-:month-:day-:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from